### ISSUE TITLE
treesitter.get_node fail because lang is not passed

### ISSUE THREAD

**Issue by pierrekttipay** [VPavliashvili/json-nvim#1]
I am selecting the simple json object and run the :JsonFormatSelection command

<img width="1616" alt="Screenshot 2024-06-01 at 22 55 17" src="https://github.com/VPavliashvili/json-nvim/assets/160447832/6279732e-f1df-4a22-87c9-436562160d44">

The file is name `laravel.log` and that why it is failing.
Repeating the same process after renaming this file: `laravel.json` works
It's a shame though, we are formatting JSON so we could pass the `lang` to treesitter independently of the file extension.

<img width="395" alt="Screenshot 2024-06-01 at 22 59 59" src="https://github.com/VPavliashvili/json-nvim/assets/160447832/5ab15b61-b3a5-4a53-8871-0265421b57e7">

**Comment by VPavliashvili** [comment]
Hello
It is failing because your buffer filetype is not set to `json`. As I have mentioned in [prerequisites section in readme](https://github.com/VPavliashvili/json-nvim?tab=readme-ov-file#prerequisites), the filetype of the buffer must be a `json`. That's why I have mentioned there [`:h filetype`](https://neovim.io/doc/user/filetype.html#filetypes) command.

Generally you don't need to rename file and set it's extention to `.json`, running `set filetype=json` inside buffer will be sufficient.

**Comment by VPavliashvili** [comment]
after [this commit](https://github.com/VPavliashvili/json-nvim/commit/3475404702bc11c3efe983c3bd46b2b176ceaf10) user will see an agreement prompt and if type `y` buffer `filetype` will set to `json` and then will proceed the requested operation.

closing the issue
